# Generated by Django 3.1.4 on 2020-12-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32)),
                ('pic1', models.CharField(max_length=40)),
                ('pic2', models.CharField(max_length=40)),
                ('pic3', models.CharField(max_length=40)),
                ('pic4', models.CharField(max_length=40)),
            ],
        ),
    ]
