# Generated by Django 3.1.4 on 2020-12-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('problem', models.CharField(max_length=320)),
                ('selA', models.CharField(max_length=40)),
                ('selB', models.CharField(max_length=40)),
                ('selC', models.CharField(max_length=40)),
                ('selD', models.CharField(max_length=40)),
                ('type', models.IntegerField()),
                ('answer', models.IntegerField()),
            ],
        ),
    ]
